In [1]:
import pandas as pd 

movies = pd.read_csv("data/movies.csv")
ratings = pd.read_csv("data/ratings.csv")

print("Movies:")
display(movies.head(10))

print("Ratings:")
display(ratings.head(10))

Movies:

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

Ratings:

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [7]:
user_movie_matrix = ratings.pivot_table(
    index='userId',
    columns='movieId',
    values='rating'
)

display(user_movie_matrix.head(10))

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,4.0,5.0,3.0,5.0,4.0,4.0,3.0,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
user_movie_filled = user_movie_matrix.fillna(0)

display(user_movie_filled.head(10))

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,4.0,5.0,3.0,5.0,4.0,4.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

user_similarity = cosine_similarity(user_movie_filled)

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_movie_matrix.index,
    columns=user_movie_matrix.index
)

display(user_similarity_df.head(5))

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

In [26]:
def get_similar_users(user_id, n=10):

    if user_id not in user_similarity_df.index:
        return "Invalid user ID"

    similar_users = user_similarity_df[user_id].sort_values(ascending=False)

    similar_users = similar_users.iloc[1:n+1]

    return similar_users

In [48]:
get_similar_users(1, 5)

userId
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
Name: 1, dtype: float64

In [60]:
movie_rating_counts = ratings.groupby('movieId').size()

In [ ]:
def recommend_movies(user_id, n_movies=10, min_ratings=20):

    if user_id not in user_movie_matrix.index:
        return "Invalid user ID"
    
    similar_users = get_similar_users(user_id)

    similar_users_ratings = user_movie_matrix.loc[similar_users.index]

    mean_ratings = similar_users_ratings.mean(axis=0, skipna=True)

    watched_movies = user_movie_matrix.loc[user_id].dropna().index

    recommendations = mean_ratings.drop(watched_movies)

    recommendations = recommendations[
        movie_rating_counts[recommendations.index] >= min_ratings
    ]

    recommendations = recommendations.sort_values(ascending=False).head(n_movies)

    recommended_movies = movies[movies['movieId'].isin(recommendations.index)][['movieId', 'title']].copy()

    recommended_movies['predicted_rating'] = recommended_movies['movieId'].map(recommendations).round(4)

    recommended_movies = recommended_movies.sort_values(by='predicted_rating', ascending=False).reset_index(drop=True)

    return recommended_movies

In [97]:
recommend_movies(1, n_movies=10, min_ratings=20)

   movieId                                  title  predicted_rating
0     1244                       Manhattan (1979)               5.0
1     1333                      Birds, The (1963)               5.0
2     1449             Waiting for Guffman (1996)               5.0
3     2067                  Doctor Zhivago (1965)               5.0
4     3100        River Runs Through It, A (1992)               5.0
5     3108                Fisher King, The (1991)               5.0
6     4734  Jay and Silent Bob Strike Back (2001)               5.0
7     7387                Dawn of the Dead (1978)               5.0
8    53322                Ocean's Thirteen (2007)               5.0
9    54272             Simpsons Movie, The (2007)               5.0

In [89]:
def weighted_recommend_movies(user_id, n_movies=10, min_ratings=20):

     if user_id not in user_movie_matrix.index:
        return "Invalid user ID"
     
     similar_users = get_similar_users(user_id)

     similarity_scores = similar_users.values

     similar_users_ratings = user_movie_matrix.loc[similar_users.index]

     weighted_ratings  = similar_users_ratings.mul(similarity_scores, axis=0)

     weighted_sum = weighted_ratings.sum(axis=0)

     similarity_sum = (
         similar_users_ratings.notna()
         .mul(similarity_scores, axis=0)
         .sum(axis=0)
     )

     weighted_average = weighted_sum / similarity_sum

     watched_movies = user_movie_matrix.loc[user_id].dropna().index
     
     recommendations = weighted_average.drop(watched_movies)

     recommendations = recommendations[
        movie_rating_counts[recommendations.index] >= min_ratings
    ]
     
     recommendations = recommendations.sort_values(ascending=False).head(n_movies)

     recommended_movies = movies[movies['movieId'].isin(recommendations.index)][['movieId', 'title']].copy()

     recommended_movies['predicted_rating'] = recommended_movies['movieId'].map(recommendations).round(4)
     
     recommended_movies = recommended_movies.sort_values(by='predicted_rating', ascending=False).reset_index(drop=True)

     return recommended_movies

In [96]:
weighted_recommend_movies(1, n_movies=10, min_ratings=20)

   movieId                                  title  predicted_rating
0     1104       Streetcar Named Desire, A (1951)               5.0
1     1235                Harold and Maude (1971)               5.0
2     4015           Dude, Where's My Car? (2000)               5.0
3     4718                  American Pie 2 (2001)               5.0
4     4734  Jay and Silent Bob Strike Back (2001)               5.0
5     7173                Along Came Polly (2004)               5.0
6     7387                Dawn of the Dead (1978)               5.0
7    53322                Ocean's Thirteen (2007)               5.0
8    54272             Simpsons Movie, The (2007)               5.0
9    57669                       In Bruges (2008)               5.0

In [99]:
user_mean_ratings = user_movie_matrix.mean(axis=1)

display(user_mean_ratings.head(10))

userId
1     4.366379
2     3.948276
3     2.435897
4     3.555556
5     3.636364
6     3.493631
7     3.230263
8     3.574468
9     3.260870
10    3.278571
dtype: float64

In [ ]:
normalized_matrix = user_movie_matrix.sub(user_mean_ratings, axis=0)

display(normalized_matrix.head(10))

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.366379,NaN,-0.366379,NaN,NaN,-0.366379,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.363636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,0.506369,1.506369,-0.493631,1.506369,0.506369,0.506369,-0.493631,NaN,-0.493631,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.269737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,0.425532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.574468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
normalized_filled = normalized_matrix.fillna(0)

display(normalized_filled.head(10))

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.366379,0.000000,-0.366379,0.000000,0.000000,-0.366379,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.363636,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.000000,0.506369,1.506369,-0.493631,1.506369,0.506369,0.506369,-0.493631,0.0,-0.493631,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1.269737,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.000000,0.425532,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,-1.574468,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [104]:
normalized_similarity = cosine_similarity(normalized_filled)

normalized_similarity_df = pd.DataFrame(
    normalized_similarity,
    index=user_movie_matrix.index,
    columns=user_movie_matrix.index
)

display(normalized_similarity_df.head(10))

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.001265,0.000553,0.048419,0.021847,-0.045497,-0.006200,0.047013,0.019510,-0.008754,...,0.018127,-0.017172,-0.015221,-0.037059,-0.029121,0.012016,0.055261,0.075224,-0.025713,0.010932
2,0.001265,1.000000,0.000000,-0.017164,0.021796,-0.021051,-0.011114,-0.048085,0.000000,0.003012,...,-0.050551,-0.031581,-0.001688,0.000000,0.000000,0.006226,-0.020504,-0.006001,-0.060091,0.024999
3,0.000553,0.000000,1.000000,-0.011260,-0.031539,0.004800,0.000000,-0.032471,0.000000,0.000000,...,-0.004904,-0.016117,0.017749,0.000000,-0.001431,-0.037289,-0.007789,-0.013001,0.000000,0.019550
4,0.048419,-0.017164,-0.011260,1.000000,-0.029620,0.013956,0.058091,0.002065,-0.005874,0.051590,...,-0.037687,0.063122,0.027640,-0.013782,0.040037,0.020590,0.014628,-0.037569,-0.017884,-0.000995
5,0.021847,0.021796,-0.031539,-0.029620,1.000000,0.009111,0.010117,-0.012284,0.000000,-0.033165,...,0.015964,0.012427,0.027076,0.012461,-0.036272,0.026319,0.031896,-0.001751,0.093829,-0.000278
6,-0.045497,-0.021051,0.004800,0.013956,0.009111,1.000000,0.004709,-0.075888,-0.000026,0.023661,...,-0.015571,-0.002229,-0.014805,-0.033564,0.016815,-0.009137,0.045501,0.021727,0.053017,0.009603
7,-0.006200,-0.011114,0.000000,0.058091,0.010117,0.004709,1.000000,0.031098,0.064350,-0.023849,...,-0.037080,0.050746,0.036846,0.020249,0.108622,0.028326,0.030981,0.028414,0.008754,0.068430
8,0.047013,-0.048085,-0.032471,0.002065,-0.012284,-0.075888,0.031098,1.000000,0.000000,-0.013390,...,0.075826,0.125282,0.025362,0.189485,-0.021220,0.022277,0.048822,0.071759,0.077180,0.017144
9,0.019510,0.000000,0.000000,-0.005874,0.000000,-0.000026,0.064350,0.000000,1.000000,0.021207,...,0.024267,0.001060,0.008300,0.006073,0.073408,0.031633,-0.012161,0.032783,0.000000,0.051898
10,-0.008754,0.003012,0.000000,0.051590,-0.033165,0.023661,-0.023849,-0.013390,0.021207,1.000000,...,-0.099928,-0.025856,-0.034765,-0.037074,0.027790,-0.039946,-0.017656,-0.052000,-0.040090,-0.026004

In [105]:
def get_normalized_similar_users(user_id, n=10):

    if user_id not in normalized_similarity_df.index:
        return "Invalid user ID"

    similar_users = normalized_similarity_df[user_id].sort_values(ascending=False)

    similar_users = similar_users.iloc[1:n+1]

    return similar_users

In [160]:
def normalized_weighted_recommend_movies(user_id, n_movies=10, min_ratings=20):

    if user_id not in user_movie_matrix.index:
        return "Invalid user ID"
    
    similar_users = get_normalized_similar_users(user_id, n=50)

    similarity_scores = similar_users.values

    similar_users_ratings = normalized_matrix.loc[similar_users.index]

    weighted_ratings = similar_users_ratings.mul(similarity_scores, axis=0)

    weighted_sum = weighted_ratings.sum(axis=0)

    similarity_sum = (
        similar_users_ratings.notna()
        .mul(similarity_scores, axis=0)
        .sum(axis=0)
        )

    predicted_scores = weighted_sum / similarity_sum

    predicted_scores = predicted_scores + user_mean_ratings[user_id]

    predicted_scores = (predicted_scores / predicted_scores.max()) * 5

    predicted_scores = predicted_scores.clip(0.5, 5)

    watched_movies = user_movie_matrix.loc[user_id].dropna().index

    recommendations = predicted_scores.drop(watched_movies)

    recommendations = recommendations[
        movie_rating_counts[recommendations.index] >= min_ratings
        ]

    recommendations = recommendations.sort_values(ascending=False).head(n_movies)

    recommended_movies = movies[movies['movieId'].isin(recommendations.index)][['movieId', 'title']].copy()

    recommended_movies['predicted_rating'] = recommended_movies['movieId'].map(recommendations).round(4)

    recommended_movies = recommended_movies.sort_values(by='predicted_rating', ascending=False).reset_index(drop=True)

    return recommended_movies

In [170]:
normalized_weighted_recommend_movies(1, n_movies=30, min_ratings=20)

,movieId,title,predicted_rating
0,64969,Yes Man (2008),4.6565
1,122882,Mad Max: Fury Road (2015),4.4866
2,148626,"Big Short, The (2015)",4.4866
3,139385,The Revenant (2015),4.4866
4,134130,The Martian (2015),4.4866
5,78499,Toy Story 3 (2010),4.4124
6,104841,Gravity (2013),4.4124
7,916,Roman Holiday (1953),4.4049
8,97938,Life of Pi (2012),4.3162
9,102407,"Great Gatsby, The (2013)",4.3004
10,106918,"Secret Life of Walter Mitty, The (2013)",4.2490
11,99114,Django Unchained (2012),4.2003
12,109487,Interstellar (2014),4.2003
13,58,"Postman, The (Postino, Il) (1994)",4.1971
14,66097,Coraline (2009),4.1947
15,720,Wallace & Gromit: The Best of Aardman Animatio...,4.1844
16,81847,Tangled (2010),4.1692
17,5617,Secretary (2002),4.1655
18,7099,Nausicaä of the Valley of the Wind (Kaze no ta...,4.1597
19,27773,Old Boy (2003),4.1546
20,1199,Brazil (1985),4.1502
21,858,"Godfather, The (1972)",4.1476
22,3910,Dancer in the Dark (2000),4.1458
23,2019,Seven Samurai (Shichinin no samurai) (1954),4.1380
24,5618,Spirited Away (Sen to Chihiro no kamikakushi) ...,4.1277
25,750,Dr. Strangelove or: How I Learned to Stop Worr...,4.1227
26,1235,Harold and Maude (1971),4.1197
27,89492,Moneyball (2011),4.1111
28,67255,"Girl with the Dragon Tattoo, The (Män som hata...",4.1111
29,93840,"Cabin in the Woods, The (2012)",4.1111